apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-chart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
  annotations:
    {{- include "my-chart.helmAnnotations" . | nindent 4 }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.ingress.annotations.authSecret }}
    nginx.ingress.kubernetes.io/auth-realm: {{ .Values.ingress.annotations.authRealm | quote }}

spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hosts | first }}
      secretName: {{ include "my-chart.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.hosts | first }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "my-chart.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
