import { Project } from '@/interfaces/app.interface';

export const initialData: Project[] = [
	{
		id: 123,
		title: 'CoSpring OLV campaign',
		assignee: 'Assigned to me',
		clientName: 'The Coca Cola Company',
		clientContact: 'Emily Smith, Internal comms manager',
		status: 'RFP',
		cost: 32620.8,
		expenses: 20727,
		profit: 11893.8,
		deadline: 'May 21, 2024',
		createdAt: 'Mar 11, 2024',
	},
	{
		id: 124,
		title: 'Winter Engagement Drive',
		assignee: 'Assigned to Emily Smith',
		clientName: 'The Coca Cola Company',
		clientContact: 'Emily Smith, Internal comms manager',
		status: 'Reviewing',
		cost: 32620.8,
		expenses: 20727,
		profit: 11893.8,
		deadline: 'May 21, 2024',
		createdAt: 'Mar 11, 2024',
	},
	{
		id: 125,
		title: 'Autumn Digital Surge',
		assignee: 'Assigned to me',
		clientName: 'The Coca Cola Company',
		clientContact: 'Emily Smith, Internal comms manager',
		status: 'Ongoing',
		cost: 32620.8,
		expenses: 20727,
		profit: 11893.8,
		deadline: 'May 21, 2024',
		createdAt: 'Mar 11, 2024',
	},
	{
		id: 126,
		title: 'Summer Breeze Outreach',
		assignee: 'Assigned to Michael Johnson',
		clientName: 'The Coca Cola Company',
		clientContact: 'Emily Smith, Internal comms manager',
		status: 'Ongoing',
		cost: 32620.8,
		expenses: 20727,
		profit: 11893.8,
		deadline: 'May 21, 2024',
		createdAt: 'Mar 11, 2024',
	},
];
