replicaCount: 1

image:
  repository: ghcr.io/aivus-co/aivus-web
  pullPolicy: Always
  tag: latest

nameOverride: "aivus-web"
fullnameOverride: "aivus-web"

namespace:
  create: false
  name: app-main

deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  hosts:
    - host: stag.aivus.app
      paths:
        - path: /
          pathType: Prefix

imagePullSecrets:
  - name: github-container-registry
