export const POLL_INTERVAL_MS = 1500;
export const POLL_TIMEOUT_MS = 180000;

export const MESSAGE_LIMIT_AUTH = 100;
export const MESSAGE_LIMIT_ANON = 50;
export const MAX_ATTACHMENTS_AUTH = 10;
export const MAX_ATTACHMENTS_ANON = 3;

export const FINALIZING_STAGE_KEYS = [
  'BRIEF_V3_FINALIZING_STAGE_ANALYZING',
  'BRIEF_V3_FINALIZING_STAGE_BRIEF',
  'BRIEF_V3_FINALIZING_STAGE_EMAIL',
  'BRIEF_V3_FINALIZING_STAGE_REVIEW',
] as const;

export const FINALIZING_STAGE_TOTAL_MS = 60_000;
export const FINALIZING_PROGRESS_CEILING = 95;
